### İSTEK ATILACAK URL
@BASE_URL = http://127.0.0.1:3000



### ANASAYFA İSTEĞİ
GET {{BASE_URL}}



### ABOUT SAYFASI İSTEĞİ
GET {{BASE_URL}}/about



### YENİ KURS OLUŞTURMA
POST {{BASE_URL}}/courses
Content-Type: application/json

{
    "name" : "C/C++",
    "description" : "Temel Algoritmalar geliştirerek programlamanın temellerini öğrenin.",
    "category" : "635fcacdfbbe5bded131dc2c"
}



### TÜM KURSLARI GETİRME
GET {{BASE_URL}}/courses

### Web sitelerine işlevsellik katmak için kullanılan bir dil olan Javascript'in temellerini öğrenmiş olacaksınız
### Javascript konusunda uzmanlaşmak isteyenler için hazırlanmış bir kurs
### Javascript'i sadece Frontend tarafında değil, aynı zamanda Backend tarafında da kullanmak istiyorsanız bu kurs tam size göre
### Günümüzde en çok kullanılan NoSQL veritabanını A'dan Z'ye öğreneceksiniz.



### TÜM KATEGORİLERİ GETİRME
POST {{BASE_URL}}/categories
Content-Type: application/json

{
    "name" : "Yapay Zeka"
}




###
GET {{BASE_URL}}/99?sortBy=name


###
POST {{BASE_URL}}
Content-Type: application/x-www-form-urlencoded

isim=cebrail&yas=29



###
PATCH {{BASE_URL}}/api/users/635189e437dd99969b2f0774
Content-Type: application/json

{
    // "_id" : "635189e437dd99969b2f0774"
    "email" : "cc4"
}



###
DELETE {{BASE_URL}}/api/users/63514de327041cc1c452177
Content-Type: application/json

